/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 cdl.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function CDL(props) {
  const { nodes, materials } = useGLTF('/cdl_centered.glb')

  const ref = useRef();

  useFrame((state, delta) => (ref.current.rotation.z += (delta*0.5)))
  return (
    <group {...props} dispose={null} ref={ref} rotation={[Math.PI/2, 0, 0]}>
      <mesh geometry={nodes.Curve.geometry} material={materials.white} scale={30} />
      <mesh geometry={nodes.Curve001.geometry} material={materials.white} scale={30} />
      <mesh geometry={nodes.Curve002.geometry} material={materials.white} scale={30} />
      <mesh geometry={nodes.Curve003.geometry} material={materials.white} scale={30} />
    </group>
  )
}

useGLTF.preload('/cdl_centered.glb')
