/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 magnifying_glass.glb
Author: justincrazyeyes (https://sketchfab.com/justincrazyeyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magnifying-glass-ed7b462d7ddd422c8c84e5ab9ebf82d2
Title: Magnifying Glass
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Mag(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/magnifying_glass.glb')

  const ref = useRef();

  useFrame((state, delta) => (ref.current.rotation.y += (delta*0.5)))

  return (
    <group {...props} dispose={null} ref={ref} scale={[0.1, 0.1, 0.1]}>
      <group position={[15, -20, 0]} rotation={[0, 0, Math.PI/4]} scale={0.24}>
        <group position={[0, 133.311, -4.852]}>
          <mesh geometry={nodes['MagnifyingGlass_Material_#31_0'].geometry} material={materials.Material_31} />
          <mesh geometry={nodes['MagnifyingGlass_Material_#30_0'].geometry} material={materials.Material_30} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/magnifying_glass.glb')
