/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 sale.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Sale(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/sale.glb')

  const ref = useRef();

  useFrame((state, delta) => (ref.current.rotation.z += (delta*0.5)))

  return (
    <group {...props} dispose={null} ref={ref} rotation={[Math.PI/2, 0, 0]}>
      <mesh geometry={nodes.sale.geometry} material={materials.sale} position={[0, 0.01, 0]} />
      <mesh geometry={nodes.sale001.geometry} material={materials['sale.001']} rotation={[0, 0, -3.131]} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/sale.glb')
