/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 server.glb
Author: MRowa (https://sketchfab.com/MRowa)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/server-0516ceb2490949428011679fb8bacb0d
Title: Server
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Server(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/server.glb')

  const ref = useRef();

  useFrame((state, delta) => (ref.current.rotation.y += (delta*0.5)))

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes.Server_Body_Placeable_0.geometry} material={materials.Placeable} rotation={[-Math.PI / 2, 0, 0]} scale={1} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/server.glb')
