/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 valorant_logo.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Valorant(props) {
  const { nodes, materials } = useGLTF('/valorant_logo.glb')

  const ref = useRef();

  useFrame((state, delta) => (ref.current.rotation.y += (delta*0.5)))

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes.VALORANT_LOGO_Material003_0.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/valorant_logo.glb')
